# Generated by Django 5.1.4 on 2025-05-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
    ]
