# Generated by Django 5.1.4 on 2025-08-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Afname', models.CharField(max_length=50)),
                ('Alname', models.CharField(max_length=50)),
                ('Adob', models.DateField()),
                ('Aage', models.IntegerField()),
                ('Aemail', models.EmailField(max_length=254, unique=True)),
                ('Apassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Cemail', models.EmailField(max_length=254)),
                ('Cphone', models.IntegerField()),
                ('Cmessage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_login', models.CharField(blank=True, max_length=255)),
                ('User_login_time', models.DateTimeField(blank=True, null=True)),
                ('User_settings', models.CharField(blank=True, max_length=255)),
                ('User_settings_time', models.DateTimeField(blank=True, null=True)),
                ('User_home', models.CharField(blank=True, max_length=255)),
                ('User_home_time', models.DateTimeField(blank=True, null=True)),
                ('Capture_traffic', models.CharField(blank=True, max_length=255)),
                ('Capture_traffic_time', models.DateTimeField(blank=True, null=True)),
                ('Charts', models.CharField(blank=True, max_length=255)),
                ('Charts_time', models.DateTimeField(blank=True, null=True)),
                ('Csv_file_editor', models.CharField(blank=True, max_length=255)),
                ('Csv_file_editor_time', models.DateTimeField(blank=True, null=True)),
                ('RealTime_Traffic', models.CharField(blank=True, max_length=255)),
                ('RealTime_Traffic_time', models.DateTimeField(blank=True, null=True)),
                ('DDOS_Home', models.CharField(blank=True, max_length=255)),
                ('DDOS_Home_time', models.DateTimeField(blank=True, null=True)),
                ('Manual_detection', models.CharField(blank=True, max_length=255)),
                ('Manual_detection_time', models.DateTimeField(blank=True, null=True)),
                ('DDOS_Report', models.CharField(blank=True, max_length=255)),
                ('DDOS_Report_time', models.DateTimeField(blank=True, null=True)),
                ('DDOS_AI_Report', models.CharField(blank=True, max_length=255)),
                ('DDOS_AI_Report_time', models.DateTimeField(blank=True, null=True)),
                ('User_logout', models.CharField(blank=True, max_length=255)),
                ('User_logout_time', models.DateTimeField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='user.user')),
            ],
        ),
    ]
